/**
 * Map filename strings to World-Level numbers
 */
module.exports = new Map([
  // World 1
  ["/ExchikkeAttack", {world: 1, level: 1}],
  ["/FunwithLightning", {world: 1, level: 2}],
  ["/ElementalMastery", {world: 1, level: 3}],
  ["/ReallyBigRobots", {world: 1, level: 4}],
  ["/ReallyBigRobots-s", {world: 1, level: 4}],
  ["/Swordfighters", {world: 1, level: 5}],
  ["/CoolLasers", {world: 1, level: 5}], 
  ["/Demolition", {world: 1, level: 6}],
  ["/Combine", {world: 1, level: 7}],
  // World 2
  ["/DandelionGrove", {world: 2, level: 1}],
  ["/TreetopClimb", {world: 2, level: 2}],
  ["/WindyWoods", {world: 2, level: 2}],
  ["/PestControl", {world: 2, level: 3}],
  ["/PolymorphicInvader", {world: 2, level: 4}],
  ["/Aquamarine", {world: 2, level: 5}],
  ["/VerdantLake", {world: 2, level: 6}],
  ["/WoodlandClash", {world: 2, level: 7}],
  ["/Wetlands", {world: 2, level: 7}],
  ["/Bioweapon", {world: 2, level: 8}],
  ["/Brushfire", {world: 2, level: 9}],
  ["/BlazingCanopy", {world: 2, level: 10}],
  ["/ThermalSmackdown", {world: 2, level: 11}],
  ["/SteamingTagTeam", {world: 2, level: 11}],
  // World 3
  ["/PrecariousCatwalk", {world: 3, level: 1}],
  ["/OilRefinery", {world: 3, level: 2}],
  ["/RemoteLocation", {world: 3, level: 3}],
  ["/RemoteLocation-s", {world: 3, level: 3}],
  ["/PollutedOutskirts", {world: 3, level: 4}],
  ["/HazardousHarbinger", {world: 3, level: 5}],
  ["/SecretLab", {world: 3, level: 6}],
  ["/VolatileChemicals", {world: 3, level: 7}],
  ["/SynthesisChamber", {world: 3, level: 8}], 
  ["/InvincibleLegion", {world: 3, level: 9}],
  ["/JellyProcessingandStorage", {world: 3, level: 10}],
  ["/JellyProcessingandStoragesavant", {world: 3, level: 10}],
  ["/DANGER", {world: 3, level: 11}],
  ["/MiasmaMonster", {world: 3, level: 12}],
  ["/MiasmaMonster-s", {world: 3, level: 12}],
  // World 4
  ["/LayeredDescent", {world: 4, level: 1}],
  ["/MinerInconvenience", {world: 4, level: 2}],
  ["/TNTTunnel", {world: 4, level: 3}],
  ["/SpookySkeletonCave", {world: 4, level: 4}],
  ["/StalagmiteScramble", {world: 4, level: 5}],
  ["/DynamiteEverywhere", {world: 4, level: 6}],
  ["/Penguins101", {world: 4, level: 7}],
  ["/Electromagnets101", {world: 4, level: 7}],
  ["/Unstoppable", {world: 4, level: 8}],
  ["/Unstoppable-s", {world: 4, level: 8}],
  ["/CrystalQuarry", {world: 4, level: 9}],
  ["/ElevatorShaft", {world: 4, level: 10}],
  ["/SteamworkTyrant", {world: 4, level: 11}],
  // World 5
  ["/MechanicalWarehouse", {world: 5, level: 1}],
  ["/MaximumVoltage", {world: 5, level: 2}],
  ["/GrindingStation", {world: 5, level: 3}],
  ["/RecyclingCenter", {world: 5, level: 4}],
  ["/ObsoleteEngine", {world: 5, level: 5}],
  ["/HydroelectricPlant", {world: 5, level: 6}],
  ["/FactorySecurityDrone", {world: 5, level: 7}],
  ["/MegatonKick", {world: 5, level: 8}],
  ["/PenguinGolf", {world: 5, level: 8}], 
  ["/PowerLines", {world: 5, level: 9}],
  ["/SecurityTunnel", {world: 5, level: 10}],
  ["/MainReactor", {world: 5, level: 11}],
  ["/ElectricDeath", {world: 5, level: 12}],
  ["/TerminalTerminator", {world: 5, level: 12}],
  // World 6
  ["ExecutionChamber", {world: 6, level: 1}],
  ["CellBlock", {world: 6, level: 2}],
  ["AngelsBarricade", {world: 6, level: 3}],
  ["DungeonSewers", {world: 6, level: 4}],
  ["SealedPassage", {world: 6, level: 5}],
  ["TreacherousMaze", {world: 6, level: 6}],
  ["InsidiousInterceptor", {world: 6, level: 7}],
  ["PenguinVault", {world: 6, level: 8}],
  ["TotalLockdown", {world: 6, level: 9}],
  ["FreakishExperiment", {world: 6, level: 10}],
  ["FreakishExperiment-s", {world: 6, level: 10}],
  // World 7
  ["/AmethystVortex", {world: 7, level: 1}],
  ["/SparklingVoid", {world: 7, level: 2}],
  ["/ShadowZone", {world: 7, level: 3}],
  ["/WhiteRiftofSeht", {world: 7, level: 4}],
  ["/EmissaryofChaos", {world: 7, level: 5}],
  ["/Microcosm", {world: 7, level: 6}],
  ["/PenguinPopper", {world: 7, level: 7}],
  ["/ErsatzTemple", {world: 7, level: 8}],
  ["/EtherealRealm", {world: 7, level: 9}],
  ["/InShiningArmor", {world: 7, level: 10}],
  // World 8
  ["MistyMoat", {world: 8, level: 1}],
  ["CourtyardCombat", {world: 8, level: 2}],
  ["WayoftheWarrior", {world: 8, level: 3}],
  ["Checkmate", {world: 8, level: 4}],
  ["OvertheWall", {world: 8, level: 5}],
  ["OvertheWall-s", {world: 8, level: 5}],
  ["EntertheStronghold", {world: 8, level: 6}],
  ["ToArms", {world: 8, level: 7}],
  ["GrandHall", {world: 8, level: 8}],
  ["HiddenAnnex", {world: 8, level: 9}],
  ["arikan", {world: 8, level: 10}],
  ["arikan-s", {world: 8, level: 10}],
  // World 9
  ["/DefendtheMountain", {world: 9, level: 1}],
  ["/AirshipAssault", {world: 9, level: 2}],
  ["/UpperAtmosphere", {world: 9, level: 3}],
  ["/SkyGarden", {world: 9, level: 4}],
  ["/Stormkeeper", {world: 9, level: 5}],
  ["/AsteroidClimb", {world: 9, level: 6}],
  ["/Vertigo", {world: 9, level: 7}],
  ["/MeteorBreaker", {world: 9, level: 8}],
  ["/TimeandSpace", {world: 9, level: 9}],
  ["/HyperspaceEngine", {world: 9, level: 10}],
  ["/HyperspaceEngine-s", {world: 9, level: 10}],
  ["/CrabMothership", {world: 9, level: 11}],
  ["/DefensiveMatrix", {world: 9, level: 12}], 
  ["/CosmicDecimator", {world: 9, level: 13}],
  // World 10
  ["/CityLimits", {world: 10, level: 1}],
  ["/RooftopHavoc", {world: 10, level: 2}],
  ["/76GoldenrodLane", {world: 10, level: 3}],
  ["/ApartmentComplex", {world: 10, level: 4}],
  ["/ParkingGarage", {world: 10, level: 5}],
  ["/HarborBattle", {world: 10, level: 5}],
  ["/DemolishedDistrict", {world: 10, level: 6}],
  ["/DilapidatedSkyscraper", {world: 10, level: 7}],
  ["/UnleashthePenguin", {world: 10, level: 8}], 
  ["/PleasantPark", {world: 10, level: 9}],
  ["/Metropolis", {world: 10, level: 10}],
  ["/Warzone", {world: 10, level: 11}],
  ["/superrobots", {world: 10, level: 12}],
  // World 11
  ["/FrostyRiver", {world: 11, level: 1}],
  ["/IcyBlockade-s", {world: 11, level: 1}],
  ["/IcyBlockade", {world: 11, level: 2}],
  ["IceCubed", {world: 11, level: 2}],
  ["SnowballFight", {world: 11, level: 3}],
  ["FrozenFiend", {world: 11, level: 4}],
  ["AncientCubes", {world: 11, level: 5}],
  ["CrimsonDolls", {world: 11, level: 6}],
  ["PerilousRuins", {world: 11, level: 7}],
  ["ToggleTemple", {world: 11, level: 7}],
  ["LostGarden", {world: 11, level: 8}], 
  ["JinxedCorridor", {world: 11, level: 9}],
  ["TheSnakePit", {world: 11, level: 10}],
  ["TreasureChamber", {world: 11, level: 11}],
  ["TreasureChamber-s", {world: 11, level: 11}],
  ["PharaohofFlame", {world: 11, level: 12}],
  // World 12
  ["BoardingtheFyskir", {world: 12, level: 0}],
  ["BoardingtheFyskirsavant", {world: 12, level: 0}],
  ["HangarBay", {world: 12, level: 1}],
  ["HangarBaysavant", {world: 12, level: 1}],
  ["EngineRoom", {world: 12, level: 2}],
  ["EngineRoomsavant", {world: 12, level: 2}],
  ["CargoHold", {world: 12, level: 3}],
  ["WeaponsLab", {world: 12, level: 3}],
  ["BattleStations", {world: 12, level: 4}],
  ["BattleStationssavant", {world: 12, level: 4}],
  ["BallisticArsenal", {world: 12, level: 5}],
  ["BallisticArsenalsavant", {world: 12, level: 5}],
  ["ControlTower", {world: 12, level: 6}],
  ["ControlTowersavant", {world: 12, level: 6}],
  ["FinalMission", {world: 12, level: 7}],
  // World Extra
  ["TheDarkDoor", {world: "Extra", level: 1}],
  ["OceanofDarkness", {world: "Extra", level: 2}],
  ["VampiresCastle", {world: "Extra", level: 3}],
  ["DevilsMachine", {world: "Extra", level: 4}],
  ["PathofSorrow", {world: "Extra", level: 5}],
  ["RedMirage", {world: "Extra", level: 6}],
  ["exgal", {world: "Extra", level: 7}]
  ])